INSERT INTO tbl_cards (
    hp,
    name,
    type_id,
    stage_id,
    info,
    attack,
    damage,
    weak,
    ressis,
    retreat,
    cardNumberInCollection,
    collection_id
)
VALUES
    (
        80,
        'Alakazam',
        5,
        3,
        'Psychic Pokémon',
        'Confuse Ray',
        '30',
        'Psychic',
        NULL,
        '3',
        1,
        1
    ),
    (
        100,
        'Blastoise',
        2,
        3,
        'Shellfish Pokémon',
        'Hydro Pump',
        '40+',
        'Lightning',
        NULL,
        '3',
        2,
        1
    ),
    (
        120,
        'Chansey',
        7,
        1,
        'Egg Pokémon',
        'Double-edge',
        '80',
        'Fighting',
        'Psychic',
        '1',
        3,
        1
    ),
    (
        120,
        'Charizard',
        1,
        3,
        'Flame Pokémon',
        'Fire Spin',
        '100',
        'Water',
        'Fighting',
        '3',
        4,
        1
    ),
    (
        40,
        'Clefairy',
        7,
        1,
        'Fairy Pokémon',
        'Metronome',
        NULL,
        'Fighting',
        'Psychic',
        '1',
        5,
        1
    ),
    (
        100,
        'Gyarados',
        2,
        2,
        'Atrocious Pokémon',
        'Dragon Rage',
        '50',
        'Grass',
        'Fighting',
        '3',
        6,
        1
    ),
    (
        70,
        'Hitmonchan',
        6,
        1,
        'Punching Pokémon',
        'Special Punch',
        '40',
        'Psychic',
        NULL,
        '2',
        7,
        1
    ),
    (
        100,
        'Machamp',
        6,
        3,
        'Superpower Pokémon',
        'Seismic Toss',
        '60',
        'Psychic',
        NULL,
        '3',
        8,
        1
    ),
    (
        60,
        'Magneton',
        4,
        2,
        'Magnet Pokémon',
        'Selfdestruct',
        '80',
        'Fighting',
        NULL,
        '1',
        9,
        1
    ),
    (
        60,
        'Mewtwo',
        5,
        1,
        'Genetic Pokémon',
        'Psychic',
        '10+',
        'Psychic',
        NULL,
        '3',
        10,
        1
    ),
    (
        90,
        'Nidoking',
        3,
        3,
        'Drill Pokémon',
        'Thrash',
        '30+',
        'Psychic',
        NULL,
        '3',
        11,
        1
    ),
    (
        80,
        'Ninetales',
        1,
        2,
        'Fox Pokémon',
        'Fire Blast',
        '80',
        'Water',
        NULL,
        '1',
        12,
        1
    ),
    (
        90,
        'Poliwrath',
        2,
        3,
        'Tadpole Pokémon',
        'Water Gun',
        '30+',
        'Grass',
        NULL,
        '3',
        13,
        1
    ),
    (
        80,
        'Raichu',
        4,
        2,
        'Mouse Pokémon',
        'Thunder',
        '60',
        'Fighting',
        NULL,
        '1',
        14,
        1
    ),
    (
        100,
        'Venusaur',
        3,
        3,
        'Seed Pokémon',
        'Solarbeam',
        '60',
        'Fire',
        NULL,
        '2',
        15,
        1
    ),
    (
        90,
        'Zapdos',
        4,
        1,
        'Electric Pokémon',
        'Thunder',
        '60',
        NULL,
        'Fighting',
        '3',
        16,
        1
    ),
    (
        80,
        'Beedrill',
        3,
        3,
        'Poison Bee Pokémon',
        'Twineedle',
        '30x',
        'Fire',
        'Fighting',
        '0',
        17,
        1
    ),
    (
        80,
        'Dragonair',
        7,
        2,
        'Dragon Pokémon',
        'Slam',
        '30x',
        NULL,
        'Psychic',
        '2',
        18,
        1
    ),
    (
        70,
        'Dugtrio',
        6,
        2,
        'Mole Pokémon',
        'Earthquake',
        '70',
        'Grass',
        'Lightning',
        '2',
        19,
        1
    ),
    (
        70,
        'Electabuzz',
        4,
        1,
        'Electric Pokémon',
        'Thunderpunch',
        '30+',
        'Fighting',
        NULL,
        '2',
        20,
        1
    );