INSERT INTO tbl_cards (
    hp,
    name,
    type_id,
    stage_id,
    info,
    attack,
    damage,
    weak,
    ressis,
    retreat,
    cardNumberInCollection,
    collection_id
)
VALUES
    (80, 'Electrode', 4, 2, 'Ball Pokémon', 'Electric Shock', '50', 'Fighting', NULL, '1', 21, 1),
    (60, 'Pidgeotto', 7, 2, 'Bird Pokémon', 'Wing Attack', '30', 'Lightning', 'Fighting', '1', 22, 1),
    (100, 'Arcanine', 1, 2, 'Legendary Pokémon', 'Flamethrower', '50', 'Water', NULL, '3', 23, 1),
    (80, 'Charmeleon', 1, 2, 'Flame Pokémon', 'Flamethrower', '50', 'Water', NULL, '1', 24, 1),
    (80, 'Dewgong', 2, 2, 'Sea Lion Pokémon', 'Aurora Beam', '50', 'Lightning', NULL, '3', 25, 1),
    (40, 'Dratini', 7, 1, 'Dragon Pokémon', 'Pound', '10', NULL, 'Psychic', '1', 26, 1),
    (50, 'Farfetch''d', 7, 1, 'Wild Duck Pokémon', 'Leek Slap', '30', 'Lightning', 'Fighting', '1', 27, 1),
    (60, 'Growlithe', 1, 1, 'Puppy Pokémon', 'Flare', '20', 'Water', NULL, '1', 28, 1),
    (60, 'Haunter', 5, 2, 'Gas Pokémon', 'Dream Eater', '50', 'Psychic', 'Fighting', '1', 29, 1),
    (60, 'Ivysaur', 3, 2, 'Seed Pokémon', 'Vine Whip', '30', 'Fire', NULL, '1', 30, 1),

    (70, 'Jynx', 5, 1, 'Human Shape Pokémon', 'Double Slap', '10x', 'Psychic', NULL, '2', 31, 1),
    (60, 'Kadabra', 5, 2, 'Psi Pokémon', 'Super Psy', '50', 'Psychic', NULL, '3', 32, 1),
    (80, 'Kakuna', 3, 2, 'Cocoon Pokémon', 'Stiffen', NULL, 'Fire', NULL, '2', 33, 1),
    (80, 'Machoke', 6, 2, 'Superpower Pokémon', 'Karate Chop', '50-', 'Psychic', NULL, '3', 34, 1),
    (30, 'Magikarp', 2, 1, 'Fish Pokémon', 'Tackle', '10', 'Lightning', NULL, '1', 35, 1),
    (50, 'Magmar', 1, 1, 'Spitfire Pokémon', 'Fire Punch', '30', 'Water', NULL, '2', 36, 1),
    (60, 'Nidorino', 3, 2, 'Poison Pin Pokémon', 'Horn Attack', '30', 'Psychic', NULL, '1', 37, 1),
    (60, 'Poliwhirl', 2, 2, 'Tadpole Pokémon', 'Water Gun', '30+', 'Grass', NULL, '2', 38, 1),
    (30, 'Porygon', 7, 1, 'Virtual Pokémon', 'Conversion', NULL, 'Fighting', 'Psychic', '1', 39, 1),
    (60, 'Raticate', 7, 2, 'Mouse Pokémon', 'Super Fang', NULL, 'Fighting', 'Psychic', '1', 40, 1),

    (60, 'Seel', 2, 1, 'Sea Lion Pokémon', 'Headbutt', '10', 'Lightning', NULL, '1', 41, 1),
    (70, 'Wartortle', 2, 2, 'Turtle Pokémon', 'Bite', '40', 'Lightning', NULL, '1', 42, 1),
    (30, 'Abra', 5, 1, 'Psi Pokémon', 'Psyshock', '10', 'Psychic', NULL, '0', 43, 1),
    (40, 'Bulbasaur', 3, 1, 'Seed Pokémon', 'Leech Seed', '20', 'Fire', NULL, '1', 44, 1),
    (40, 'Caterpie', 3, 1, 'Worm Pokémon', 'String Shot', '10', 'Fire', NULL, '1', 45, 1),
    (50, 'Charmander', 1, 1, 'Lizard Pokémon', 'Ember', '30', 'Water', NULL, '1', 46, 1),
    (30, 'Diglett', 6, 1, 'Mole Pokémon', 'Dig', '10', 'Grass', 'Lightning', '0', 47, 1),
    (50, 'Doduo', 7, 1, 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Lightning', 'Fighting', '0', 48, 1),
    (50, 'Drowzee', 5, 1, 'Hypnosis Pokémon', 'Pound', '10', 'Psychic', NULL, '1', 49, 1),
    (30, 'Gastly', 5, 1, 'Gas Pokémon', 'Destiny Bond', NULL, 'Psychic', 'Fighting', '0', 50, 1);