INSERT INTO tbl_cards (
    hp,
    name,
    type_id,
    stage_id,
    info,
    attack,
    damage,
    weak,
    ressis,
    retreat,
    cardNumberInCollection,
    collection_id
)
VALUES
    (50, 'Koffing', 3, 1, 'Poison Gas Pokémon', 'Foul Gas', '10', 'Psychic', NULL, '1', 51, 1),
    (50, 'Machop', 6, 1, 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', NULL, '1', 52, 1),
    (40, 'Magnemite', 4, 1, 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', NULL, '1', 53, 1),
    (70, 'Metapod', 3, 2, 'Cocoon Pokémon', 'Stun Spore', '20', 'Fire', NULL, '2', 54, 1),
    (40, 'Nidoran Male', 3, 1, 'Poison Pin Pokémon', 'Horn Hazard', '30', 'Psychic', NULL, '1', 55, 1),
    (90, 'Onix', 6, 1, 'Rock Snake Pokémon', 'Rock Throw', '10', 'Grass', 'Lightning', '3', 56, 1),
    (40, 'Pidgey', 7, 1, 'Tiny Bird Pokémon', 'Whirlwind', '10', 'Lightning', 'Fighting', '1', 57, 1),
    (40, 'Pikachu', 4, 1, 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', NULL, '1', 58, 1),
    (40, 'Poliwag', 2, 1, 'Tadpole Pokémon', 'Water Gun', '10+', 'Grass', NULL, '1', 59, 1),
    (40, 'Ponyta', 1, 1, 'Fire Horse Pokémon', 'Flame Tail', '30', 'Water', NULL, '1', 60, 1),

    (30, 'Rattata', 7, 1, 'Mouse Pokémon', 'Bite', '20', 'Fighting', 'Psychic', '0', 61, 1),
    (40, 'Sandshrew', 6, 1, 'Mouse Pokémon', 'Sand Attack', '10', 'Grass', 'Lightning', '1', 62, 1),
    (40, 'Squirtle', 2, 1, 'Tiny Turtle Pokémon', 'Bubble', '10', 'Lightning', NULL, '1', 63, 1),
    (60, 'Starmie', 2, 2, 'Mysterious Pokémon', 'Star Freeze', '20', 'Lightning', NULL, '1', 64, 1),
    (40, 'Staryu', 2, 1, 'Star Shape Pokémon', 'Slap', '20', 'Lightning', NULL, '1', 65, 1),
    (50, 'Tangela', 3, 1, 'Vine Pokémon', 'Bind', '20', 'Fire', NULL, '2', 66, 1),
    (40, 'Voltorb', 4, 1, 'Ball Pokémon', 'Tackle', '10', 'Fighting', NULL, '1', 67, 1),
    (50, 'Vulpix', 1, 1, 'Fox Pokémon', 'Confuse Ray', '10', 'Water', NULL, '1', 68, 1),
    (40, 'Weedle', 3, 1, 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', NULL, '1', 69, 1),

    (NULL, 'Clefairy Doll', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 70, 1),
    (NULL, 'Computer Search', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 71, 1),
    (NULL, 'Devolution Spray', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 72, 1),
    (NULL, 'Imposter Professor Oak', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 73, 1),
    (NULL, 'Item Finder', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 74, 1),
    (NULL, 'Lass', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 75, 1),
    (NULL, 'Pokémon Breeder', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 76, 1),
    (NULL, 'Pokémon Trader', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 77, 1),
    (NULL, 'Scoop Up', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 78, 1),
    (NULL, 'Super Energy Removal', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 79, 1),
    (NULL, 'Defender', NULL, NULL, 'Trainer card', NULL, NULL, NULL, NULL, NULL, 80, 1);